Fix action-validator to run for each file on pre-commit hook

diff --git a/bin/run-action-validator b/bin/run-action-validator
--- a/bin/run-action-validator
+++ b/bin/run-action-validator
@@ -7,4 +7,12 @@ if ! command -v action-validator &>/dev/null; then
 	exit 1
 fi
 
-action-validator "$@"
+for file in $@
+do
+   echo "File: ${file}"
+   errors=$(action-validator $file 2>&1)
+   if [ ! -z "$errors" ]; then
+      echo "${errors}"
+      exit 1
+   fi
+done
